### ISSUE TITLE
Is possible to run the ionic-lab option with this boilerplate?

### ISSUE THREAD

**Issue by Telemakhos** [mwaylabs/generator-m#211] opened 2015-07-20 21:56 UTC
The ionic cli has an option to serve/watch both iOS and Android versions one beside the other with ```ionic serve --lab```. Can we somewhat use this in the generator-m?

**Comment by gruppjo** [comment] 2015-07-21 15:25
Hi we've been considering implementing this for quite a while (see #143). However it's not a priority right now, we're focussing on different things right now. See the current milestone for v1.3.0 https://github.com/mwaylabs/generator-m/milestones/1.3.0.

However we're always eager to learn how others are developing, so you could help us by providing some more information:

- is the ionic lab option a feature your workflow heavily relies on?
- how important is this feature in your opinion?
- how do you use this feature?

**Comment by Telemakhos** [comment] 2015-07-22 11:10
> is the ionic lab option a feature your workflow heavily relies on?
Not really, but I'm eager to use it from time to time since it seems really convenient watching how your changes will look like in both platforms.

> how important is this feature in your opinion?
I'd say is quite important like anything that saves you precious time. =)

> how do you use this feature?
I just use it every now and then to see how layout changes affect both platforms

**Comment by kschio** [comment] 2015-07-30 16:47
As I'm rarely developing for only a specific platform, live reload is a real timesaver (#19).

If I could add "--livereload" as an argument to the build task, I would be more than happy :)

**Comment by gruppjo** [comment] 2015-08-06 10:39
@Telemakhos, @kschio. Thanks for your feedback. I'll make sure this is taken into consideration in the planning of the next release. I also think this is a neat and attractive future.

**Comment by gruppjo** [comment] 2015-08-06 10:40
I'm closing this issue since it's basically a duplicate of this one: https://github.com/mwaylabs/generator-m/issues/143
Please put any further discussion, comments over there.

**Closed by gruppjo** 2015-08-06 10:40 UTC
Labels: support
